blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Question
    url: https://github.com/twocaretcat/.github/blob/main/docs/SUPPORT.md#questions
    about: Open a discussion via the Discussion tab to ask a question about the project
