name: Sync labels
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v4
      - uses: brpaz/action-label-syncer@master
        with:
          prune: false
          manifest: .github/labels.yml
          repository: |
            twocaretcat/.github
            twocaretcat/168421
            twocaretcat/astro-snapshot
            twocaretcat/better-segments-for-strava
            twocaretcat/calculator
            twocaretcat/Collage-Generator-for-Last.fm
            twocaretcat/Compare-Form-Backends
            twocaretcat/CringeCraft
            twocaretcat/dark-mode-for-outlook
            twocaretcat/dotfiles
            twocaretcat/Game-Maps
            twocaretcat/gatsby-plugin-component-to-image
            twocaretcat/gimp-average-layers
            twocaretcat/gitmojito
            twocaretcat/Image-Signer
            twocaretcat/Internal-Domain-Name-Calculator-for-TrueCharts-Apps
            twocaretcat/twocaretcat
            twocaretcat/twocaretcat.github.io
            twocaretcat/komodo
            twocaretcat/Mergist
            twocaretcat/NoBS
            twocaretcat/Playlist-Archiver-for-Spotify
            twocaretcat/rtg-for-outlook
            twocaretcat/Shared-File-Finder-for-Google-Drive
            twocaretcat/Short-End
            twocaretcat/Tally
            twocaretcat/Tally
            twocaretcat/Tally-Extension
            twocaretcat/tally-ts
            twocaretcat/tinyi18n
            twocaretcat/watch-history-exporter-for-amazon-prime-video
          token: ${{ secrets.GH_TOKEN }}
